export const ADD_ITEM_LIST = 'detail/ADD_ITEM_LIST'
export const DETELE_ITEM_LIST = 'detail/DETELE_ITEM_LIST'
export const CHANGE_DETAIL_CONTENT = 'detail/CHANGE_DETAIL_CONTENT'
export const CHANGE_PAGE = 'detail/CHANGE_PAGE'
export const CHANGE_DETAIL_BOOTON = 'detail/CHANGE_DETAIL_BOOTON'
